### ISSUE TITLE
Cannot publish and subscribe within one channel variable

### ISSUE THREAD

**Issue by swingywc** [ably/ably-js-react-native#8]
Hi Ably,
I just counter a problem and want to see if there is any solution.

my screen is going like this:

    import React, { Component } from 'react';
    import { View, TouchableOpacity, Text } from 'react-native';
    import { Realtime } from 'ably';

    class Screen extends Component {

      _sendRequestAndWait() {
        let client = new Realtime("ABLY_CLIENT_ID"),
          channel = client.channels.get("customer-ID-channel");
        channel.publish('send_payment_to_customer', {paymentId: 1, amount: 1, merchantId: 1});
        channel.subscribe('receive_response_from_customer', (message) => this._handleResponse(message));
      }

      _handleResponse(message) {
        //blah blah blah...
      }

      render() {
        return (
          <View>
            <TouchableOpacity onPress={this._sendRequestAndWait.bind(this)}>
              <Text>Click Me</Text>
            </TouchableOpacity>
          </View>
        );
      }
    }

However, the channel cannot catch the `receive_response_from_customer` sent by customer side.
My current solution will be like:

    _sendRequest() {
      let client = new Realtime("ABLY_CLIENT_ID"),
        channel = client.channels.get("customer-ID-channel");
      channel.publish('send_payment_to_customer', {paymentId: 1, amount: 1, merchantId: 1});
      
      this._waitResponse();
    }

    _waitResponse() {
      let client = new Realtime("ABLY_CLIENT_ID"),
        channel = client.channels.get("customer-ID-channel");
      channel.subscribe('receive_response_from_customer', (message) => this._handleResponse(message));
    }

This is definitely not the solution I want because a channel should able to handle publish and subscribe function together.

Therefore, I would like to ask if anyone knows what's wrong with it and how to solve it? Thanks.

## Version
`react`: `'16.2.0'`
`react-native`: `'0.52.0'`
`ably-react-native`: `'1.0.0'`

**Comment by ajchili** [comment]
I had to manually attach to the channel before subscribing to it. Hopefully, this helps.
```JavaScript
let client = new Realtime("ABLY_CLIENT_ID"),
channel = client.channels.get("customer-ID-channel");
channe.attach(err => {
  channel.subscribe(...);
  channel.publish(...);
});
```

**Comment by SimonWoolf** [comment]
Hi @swingywc . Sorry for the delay -- this was overlooked because this isn't a support forum, it's a bug tracker for the react-native wrapper. In future for support, or if you have any further questions now, please go to https://www.ably.io/support and file a support ticket, or contact us over live chat.

I'm not sure I follow exactly what you're expecting, but to the extent that the problem is that you need to ensure you receive all messages on the channel sent after your own, @ajchili 's solution is correct: you should attach to the channel first. `subscribe()` with a non-attached channel will kick off an asynchronous attach, but any messages from before the actual point of attachment may be missed. By `attach()`ing first, you ensure that you're attached at the time you publish your message. (For an attached channel, `subscribe()` is a purely local operation: it just adds a listener).

Initializing a second client library instance is definitely not a good idea, it will needlessly use up your peak connection allocation in your package. (And I don't see how it would help anyway, assuming the issue is the publish/subscribe race).
